name: Demo App Distribution

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Firebase App Dist Key File
      shell: bash
      env:
        FIREBASE_DIST_KEY: ${{ secrets.FIREBASE_DIST_KEY }}
      run: echo "$FIREBASE_DIST_KEY" | base64 -d > dist/firebase-app-dist-key.json

    - name: Build with Gradle
      run: ./gradlew assembleDebug appDistributionUploadDebug
